import * as THREE from "three";

export default{
    model:{
        model:{
            MiraiAkari:"model/MiraiAkari/MiraiAkari_v1.0.pmx",
            TokinoSora:"model/TokinoSora/ときのそら.pmx"
        },
        motion:{
            RucaRucaNightFever:"danceMotion/RucaRucaNightFever.vmd"
        },
        camera:{
            PerspectiveCamera:{
                fov:70,
                aspectX:document.body.clientWidth,
                aspectY:document.body.clientHeight,
                near:1,
                far:500
            },
            position:{
                x:0,
                y:20,
                z:20
            },
            lookAt:new THREE.Vector3(0, 10, 0)
        },
        light:{
            DirectionLight:{
                intensity:1.2
            },
            AmbientLight:{
                color:0xffffff,
                intensity:0.72
            },
            position:{
                x:20,
                y:30,
                z:20
            }
        },
        floor:{
            size:300,
            color:0xffffff,
            y:-0.01,
            reflectionColor:0xe8f8ee,
            shadowOpacity:0.28
        },
        space:{
            backgroundColor:0xf0faf0
        },
        storage:{
            key:'mmd-viewer-settings-v1'
        }
    }
}
